# This project configuration should relate only to the high level notebook api (as primary deps).
[tool.poetry]
name = "Biosimulators_smoldyn"
version = "1.5.0"
description = "Simulation Verification Service and API"
authors = ["Alex Patrie <alexanderpatrie@gmail.com>"]
readme = "README.md"
packages = [{include = "biosimulators_smoldyn"}]

[tool.poetry.dependencies]
python = ">=3.10"
# smoldyn = "*"
smoldyn = "^2.73"
biosimulators-utils = {version = "^0.1.188", extras = ["logging"]}

[tool.poetry.group.dev.dependencies]
toml = "^0.10.2"
pytest = "^8.3.2"

[tool.poetry.extras]
dev = ["api", "worker"]

[tool.pytest.ini_options]
testpaths = ["biosimulators_smoldyn"]
addopts = "--ignore=setup.py"
python_files = "test.py"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
