# This project configuration should relate only to the high level notebook api (as primary deps).
[tool.poetry]
name = "Biosimulators_smoldyn"
version = "1.5.0"
description = "BioSimulators implementation of Smoldyn"
authors = ["Alex Patrie <alexanderpatrie@gmail.com>"]
readme = "README.md"
packages = [{include = "biosimulators_smoldyn"}]

[tool.poetry.dependencies]
python = ">=3.10"
smoldyn = ">=2.73"
biosimulators-utils = {version = "^0.1.188", extras = ["logging"]}
simulariumio = "^1.11.0"

[tool.poetry.group.dev.dependencies]
toml = "^0.10.2"
pytest = "^8.3.2"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--ignore=setup.py"
python_files = "test_smoldyn.py"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
